WATCH_POLITICIANS = [
    # Most watched - proven track records
    "pelosi", "paul pelosi",
    "tuberville",
    "crenshaw",
    "collins",
    "loeffler",
    "burr",
    "greene",
    "ocasio",
    # Senate heavy traders
    "ossoff",
    "warnock",
    "kelly",
    "manchin",
    "capito",
    "inhofe",
    "lankford",
    "scott",
    "rubio",
    "warren",
    # House heavy traders  
    "mccaul",
    "gottheimer",
    "suozzi",
    "tenney",
    "self",
    "moore",
    "clyde",
    "lucas",
    "pfluger",
    "van duyne",
    "steel",
    "obernolte",
    "dunn",
    "fallon",
    "nehls",
    "good",
    "ellzey",
    "austin scott",
    "perry",
    "fitzgerald",
    "joyce",
    "johnson",
    "weber",
    "babin",
    "carter",
    "olson",
    "brady",
    "cloud",
]